name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  stream_feed_flutter_core: ^0.8.0
  provider: ^6.0.2
  cached_network_image: ^3.2.0
  custom_refresh_indicator: ^4.0.1
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  
  assets:
    - images/
